### ISSUE TITLE
1.10 Roadmap

### ISSUE THREAD

**Issue by Matsv** [MylesIsCool/ViaVersion#408]
## Please report any issues you have with the 1.10 build in the comments.

You might have noticed that there is a '1.10' branch. We are following the development for 1.10 to be compatible with it when it gets released. https://github.com/MylesIsCool/ViaVersion/tree/1.10

**Please know that this builds might be unstable and are not meant for production use.**

_We'll only support the latest snapshot, when a new one comes out, previous one will get dropped, please test it on the latest version before you report issues_

Download link: [BuildServer](https://ci.viaversion.com/job/ViaVersion%201.10%20DEV/)

**TODO:**
- [x] Fix some changed sound effects
- [x] Make it work on Spigot 1.8
- [x] Fix wrong sounds

**Comment by Matsv** [comment]
Sounds are now fixed, link is updated.

**Comment by Matsv** [comment]
Now compatible with Spigot 1.8.

**Comment by Matsv** [comment]
Updated to 16w21a

**Comment by Matsv** [comment]
Now compatible with the latest version (1.10-pre1).

**Comment by Matsv** [comment]
Sounds should work correctly now.

**Comment by SteveTheDog** [comment]
Will this be compatible with 1.9.x and 1.10 on spigot 1.8 or just 1.10?

**Comment by Matsv** [comment]
Yes :smile: spigot 1.8.8-latest 1.9

**Comment by SteveTheDog** [comment]
Ok, thank you so much!

**Comment by Matsv** [comment]
Now compatible with 1.10-pre2

**Comment by Matsv** [comment]
1.10 is out. It'll be released on Spigot soon.
