### ISSUE TITLE
Multiplatform ViaVersion - Sponge / BungeeCord / Bukkit

### ISSUE THREAD

**Issue by MylesIsCool** [MylesIsCool/ViaVersion#505]
## Please report any issues you have with the modular build in the comments.

We've been working on developing ViaVersion for Sponge and Bungee, this comes in a multiplatform jar which should work on: Sponge, Bukkit, BungeeCord.
This has been tested to work on SpongeVanilla & SpongeForge. Just drop it in your mods folder and go.
It has also been tested on BungeeCord.

_This supports the same versions as normal ViaVersion_

There are a few missing features but otherwise it should work fine.

You might have noticed that there is a '[modular' branch](https://github.com/MylesIsCool/ViaVersion/tree/modular). 

**Please know that this builds might be unstable and are not meant for production use.**

**Downloads**: [BuildServer](https://ci.viaversion.com/job/ViaVersion_Modular/lastBuild/us.myles$viaversion/)

**Sponge Thread**
https://forums.spongepowered.org/t/wip-viaversion/14928

If you run a Sponge server it would be appreciated if you could help us test ViaVersion for Sponge to ensure there are no issues. 

**TODO:**
- [x] See if CraftBukkit 1.9 is fixable (yay!)
- [x] Implement the handItem cache for Sponge
- [x] Test CommandBlock system & remove old system from listeners
- [x] Bungeecord:
  - [x] Handle unsupported protocols correctly
  - [x] Handle unregistered or failed to ping servers
  - [x] Default hand is always left
  - [x] Look into this exception: https://paste.matsv.nl/mefozohepe.avrasm 
  - [x] Look into why 16w39a is readTimeOuting (309 is changed to 210 before bungee)
  - [x] Config Option for Server Protocols
  - [x] Config Option for Searching Interval (also allows disabling, if disabled search server command says so)
  - [x] Fix magic random order @ config
  - [x] Profile / Look to reduce reflection
  - [x] Add info about server protocols to dump

**Comment by TheIntelloBox** [comment]
Is ViaVersion ready for 1.11 ? :D

**Comment by MylesIsCool** [comment]
@TheIntelloBox On the edge of, providing no major changes tomorrow.

**Comment by MylesIsCool** [comment]
Closing this issue as this has been merged with master, will be released for 1.0.0. (Hopefully today if mojang releases 1.11)
