### ISSUE TITLE
1.13 Roadmap

### ISSUE THREAD

**Issue by Matsv** [MylesIsCool/ViaVersion#819]
## Please report any issues/suggestions you have with the 1.13 build in the comments. 

You might have noticed that there is a '['dev' branch](https://github.com/MylesIsCool/ViaVersion/tree/dev). We are following the development of 1.13 to be compatible with it when it gets released. 

**Please know that this builds might be unstable and are not meant for production use.**

_We'll only support the latest snapshot, when a new one comes out, previous one will get dropped, please test it on the latest version before you report issues_

**Current compatible snapshot:** 1.13-pre7
**Downloads**: [BuildServer](https://ci.viaversion.com/job/ViaVersion-DEV/)

**TODO:**
- [x] Full block mappings check:
    - [ ] Fix north/south/east connectings for glass_pane/stone_wall/iron_bar/fences (This was handled client-sided in 1.12, server doesn't blockupdate fences around, will be a pain.) See #856 for progress.
    - [x] Fix invisible banners on placement
- [x] Full item mappings check
    - [ ] Smooth sandstone
    - [ ] custom name doesn’t show (unconfirmed)
- [x] Hunt down Advancements issue (Did the packet encoding/decoding change?)  [(Disconnect message)](https://fs.matsv.nl/media?id=auwje4z4lxw.png)
- [x] Handle AreaEffectCloud changes
- [x] Handle particle changes
- [ ] Handle sound changes
- [x] Scoreboard prefix/suffix?

 **Low prio:** 
- [ ] Server sided translations
- [ ] Statistics (worth it?)
- [ ] Noteblock particle (is it client-sided based of state now?)
- [ ] Investigate possibility to replace new blocks with air

**Comment by TNTUP** [comment]
Tried it and when I logged a 1.13-pre1 client, console spamming (probably tile entities) as I placed signs which said "unhandled" thing, if requested I can provide the log of it (tested yesterday) and sometimes when I break a block, a wrong sound/block particle is visible/playing. eg: anvil, breaks it, hears grass sound breaking/leaves particles. Hope it helps for testing :)

**Comment by Gerrygames** [comment]
The team prefix and suffix were added again in 18w20a, so this should no longer be a problem. This change is already included in the commit for 18w20b by @creeper123123321

**Comment by creeper123123321** [comment]
- [ ] Fix sidebar title (May be related with [MC-131382](https://bugs.mojang.com/browse/MC-131382))
- [ ] Think what to do with new nickname coloring based on team color instead of prefix last color

**Comment by TNTUP** [comment]
Tried Pre7 client with https://ci.viaversion.com/job/ViaVersion-DEV/139/ and it seems not to work. With pre8 it does, but looks like it hangs the server while it spams the console until I disconnect the client it goes fine ^^

**Comment by TNTUP** [comment]
The diagram on the readme file would need to be update aswell, I guess you've already know it :D

**Comment by ConnorFranta** [comment]
1.13.1 is coming soon already
https://minecraft.net/en-us/article/minecraft-snapshot-18w30a

**Comment by TNTUP** [comment]
@creeper123123321 Agreed (and sorry for late answer) but with worldedit it is possible. Probably the 1.12.2 server will deny it anyways, like you said^^

**Comment by MylesIsCool** [comment]
Closing this, we'll be following the missing specifics on separate issues :)
